DELAY=24h

MOVE_JOB1=Mover los logs de la base de datos de /tal a /tal/otro
MOVE_PRE1=su - icpadm -c "backup database ICP to /tal/destino"
MOVE_SOURCE1=/de/donde
MOVE_TARGET1=/para/donde/se/mueven
MOVE_EXPR1=S[0-9]*.LOG
MOVE_OLDER=3d

