DEBUG=True
DRY_RUN=False
DELAY=30

# REMOVE_JOB1="Remove all from /tmp/uno"
# REMOVE_SOURCE1="/tmp/uno"

COPY_JOB2="Copy all from /tmp/uno to /tmp/dos"
COPY_SOURCE2="/tmp/uno"
COPY_TARGET2="/tmp/dos"
COPY_EXPR2="*"

MOVE_JOB3="Move some from /tmp/uno to /tmp/dos"
MOVE_SOURCE3="/tmp/uno"
MOVE_TARGET3="/tmp/dos"
MOVE_EXPR3="[0-9][0-9]__*"
